### ISSUE TITLE
"Value Footnotes" type number

### ISSUE THREAD

**Issue by davbre** [datasets/population-city#2]
In the datapackage file, the "Value Footnotes" type is given as "number". I think this should be "string" as it can cite more than one footnote, in which case it is a comma delimited list of numbers. Also, I think the footnote section at the end of each csv file should be in its own csv file, and its metadata included as a separate resource in the datapackage.json file.

**Comment by Mikanebu** [comment]
@davbre Thanks for your report about this issue. I fixed it

**Comment by Mikanebu** [comment]
FIXED
